# ─── Kalki — Docker Hub publisher ──────────────────────────────────────────
#
# Builds and pushes the five Kalki service images to Docker Hub under
# docker.io/$(DOCKER_USER)/kalki-<service>:<tag>. Tags every image with both
# `latest` and a per-build $(TAG) (defaults to a UTC timestamp).
#
# Common invocations:
#
#   make help                           # this screen
#   make all                            # build + push every service
#   make bet                            # build + push one service
#   make push-backend                   # explicit form (equivalent to: make backend)
#   make image-aviator                  # symmetry alias for push-aviator
#   make build-admin                    # build locally (--load), don't push
#   make login                          # docker login docker.io
#   make clean                          # remove the kalki-builder buildx instance
#
# Variables — override via env or `make VAR=value`:
#
#   DOCKER_USER    Docker Hub account that owns the images  (default: saurav7055)
#   TAG            Image version tag                         (default: YYYYMMDDTHHMMSSZ-<git-sha7>)
#   PLATFORM       Target arch                               (default: linux/amd64)
#   BUILDER        buildx builder name                       (default: kalki-builder)
#
# Tag nomenclature matches .github/workflows/build-and-push.yml — a UTC
# timestamp (sortable lexicographically) plus the 7-char git SHA so any
# image traces back to the source commit. Every push also re-tags `:latest`,
# same as the CI workflow.
#
# Per-cluster public URLs — Next.js inlines NEXT_PUBLIC_* and Vite inlines
# VITE_* at build time, so these are baked into the client bundle. Override
# to retarget at a different cluster:
#
#   BACKEND_URL, AUCTIONS_URL, AVIATOR_URL, EXCHANGE_URL, ADMIN_URL
#   GOOGLE_ENABLED   ("false" disables the Google sign-in CTA on bet)
#   AVIATOR_ROCKET   ("1" ships the rocket art; blank = legacy plane)
#
# The per-service rules at the bottom are generated by $(eval) from a single
# template — pattern rules with .PHONY targets are broken in the GNU Make
# 3.81 that ships with macOS, and $(eval) makes the resulting rules concrete
# enough that 3.81 handles them correctly.

SERVICES := backend bet auctions aviator admin

DOCKER_USER ?= saurav7055
BUILDER     ?= kalki-builder

# Production target. The Kalki cluster runs amd64 nodes, so every image
# pushed to Docker Hub must be amd64 regardless of where the build is
# kicked off (CI runner, Intel laptop, Apple Silicon). buildx + the
# docker-container driver + QEMU make this cross-compile transparent;
# the `builder` target installs the binfmt handlers so the host kernel
# can also *run* the emulated image (needed for `build-*` --load on
# arm64 hosts; --push targets don't care because nothing lands locally).
#
# Override only if you genuinely need a different arch — multi-arch
# manifests use comma-separated lists, e.g. `PLATFORM=linux/amd64,linux/arm64`.
PLATFORM ?= linux/amd64

# Set PRUNE=0 to skip the post-push `docker system prune -f` (e.g. on a
# rapid iterative loop where you don't want to lose unrelated dangling
# images between builds). Default ON because sequential builds across the
# five services otherwise accumulate gigabytes of stale layers.
PRUNE ?= 1

# Git SHA fallback: `local` if we're outside a repo (e.g. running from a
# tarball). `:=` so the shell only runs once, not per-target.
GIT_SHA := $(shell git rev-parse --short=7 HEAD 2>/dev/null || echo local)

# Same format as the GitHub Actions build-and-push.yml `Compute tag` step:
# UTC `YYYYMMDDTHHMMSSZ` joined with the 7-char git SHA. UTC keeps the tag
# stable across timezones; lexicographic sort = chronological sort.
TAG ?= $(shell date -u +%Y%m%dT%H%M%SZ)-$(GIT_SHA)

BACKEND_URL    ?= https://kalki-backend.cloud.podstack.ai
AUCTIONS_URL   ?= https://kalki-auctions.cloud.podstack.ai
AVIATOR_URL    ?= https://kalki-aviator.cloud.podstack.ai
EXCHANGE_URL   ?= https://kalki-bet.cloud.podstack.ai
ADMIN_URL      ?= https://kalki-admin.cloud.podstack.ai
GOOGLE_ENABLED ?= false
AVIATOR_ROCKET ?= 1

# Per-service build args. Backend has none (server-side renders, reads env
# at runtime). The four UI apps each pull only the subset they actually
# reference in client code — keep this list in sync with each Dockerfile's
# ARG declarations.
BUILD_ARGS_backend  :=
BUILD_ARGS_bet      := --build-arg=NEXT_PUBLIC_AUCTIONS_URL=$(AUCTIONS_URL) \
                       --build-arg=NEXT_PUBLIC_AVIATOR_URL=$(AVIATOR_URL) \
                       --build-arg=NEXT_PUBLIC_BACKEND_URL=$(BACKEND_URL) \
                       --build-arg=NEXT_PUBLIC_GOOGLE_ENABLED=$(GOOGLE_ENABLED)
BUILD_ARGS_auctions := --build-arg=NEXT_PUBLIC_AUCTIONS_URL=$(AUCTIONS_URL) \
                       --build-arg=NEXT_PUBLIC_AVIATOR_URL=$(AVIATOR_URL) \
                       --build-arg=NEXT_PUBLIC_BACKEND_URL=$(BACKEND_URL) \
                       --build-arg=NEXT_PUBLIC_EXCHANGE_URL=$(EXCHANGE_URL) \
                       --build-arg=NEXT_PUBLIC_ADMIN_URL=$(ADMIN_URL)
BUILD_ARGS_aviator  := --build-arg=NEXT_PUBLIC_API_URL=$(BACKEND_URL) \
                       --build-arg=NEXT_PUBLIC_AUCTIONS_URL=$(AUCTIONS_URL) \
                       --build-arg=NEXT_PUBLIC_EXCHANGE_URL=$(EXCHANGE_URL) \
                       --build-arg=NEXT_PUBLIC_AVIATOR_ROCKET=$(AVIATOR_ROCKET)
BUILD_ARGS_admin    := --build-arg=VITE_API_BASE_URL=$(BACKEND_URL) \
                       --build-arg=VITE_BET_BASE_URL=$(EXCHANGE_URL)

.PHONY: help all login builder clean prune \
        $(SERVICES) \
        $(addprefix push-,$(SERVICES)) \
        $(addprefix image-,$(SERVICES)) \
        $(addprefix build-,$(SERVICES))

.DEFAULT_GOAL := help

# Build + push every service. Sequential so the buildx cache stays warm
# between layers shared across the four Next.js apps (node, prisma, etc.).
all: $(addprefix push-,$(SERVICES))

# Ensure a buildx builder exists, is selected, has booted, and the host
# kernel has binfmt handlers for $(PLATFORM). Idempotent — re-running is
# cheap. The docker-container driver (default for `buildx create`) is
# required for cross-platform builds; the default `docker` driver can
# only build for the host arch.
#
# `tonistiigi/binfmt --install $(PLATFORM)` is the official upstream way
# to register QEMU emulators on the host. On native amd64 hosts this is
# a no-op; on arm64 it makes `--load`ed amd64 images actually runnable.
builder:
	@docker buildx inspect $(BUILDER) >/dev/null 2>&1 \
	  || docker buildx create --name $(BUILDER) --driver docker-container --use
	@docker buildx use $(BUILDER) >/dev/null
	@docker buildx inspect --bootstrap >/dev/null
	@docker run --privileged --rm tonistiigi/binfmt --install $(PLATFORM) >/dev/null 2>&1 || true

login:
	docker login docker.io

# Drop the local buildx builder. Useful when caches go stale or the
# instance ends up in a bad state after a Docker Desktop upgrade.
clean:
	-docker buildx rm $(BUILDER)

# Same `docker system prune -f` the push / build targets run, exposed so
# you can reclaim disk without kicking off a build.
prune:
	docker system prune -f

# ─── Per-service rule generator ────────────────────────────────────────────
#
# For each service S, $(eval) defines four targets:
#
#   push-S    Build for $(PLATFORM), push :latest + :$(TAG), then prune
#   image-S   Alias for push-S
#   build-S   Build locally (--load) then prune — host arch must match PLATFORM
#   S         Alias for push-S (the everyday shorthand)
#
# Each push and build target runs `docker system prune -f` afterward unless
# PRUNE=0 was passed — sequential builds across the five services otherwise
# fill the host disk with dangling intermediate layers. `make prune` does
# the same thing on demand without rebuilding.
#
# Generated rules are concrete (not pattern rules), so they fire under both
# modern make and the 3.81 that ships with macOS.

# Tiny shim: a recipe line that prunes only when PRUNE != 0. `if [ … ]`
# inside a single recipe line keeps it a one-liner make can attach to the
# end of an existing target's recipe.
PRUNE_CMD = @if [ "$$(PRUNE)" != "0" ]; then \
	  echo ">>> docker system prune -f"; \
	  docker system prune -f; \
	else \
	  echo ">>> skipping prune (PRUNE=0)"; \
	fi

define SERVICE_RULES
push-$(1): builder
	docker buildx build \
	  --platform $$(PLATFORM) \
	  $$(BUILD_ARGS_$(1)) \
	  -t docker.io/$$(DOCKER_USER)/kalki-$(1):$$(TAG) \
	  -t docker.io/$$(DOCKER_USER)/kalki-$(1):latest \
	  --push \
	  ./$(1)
	@echo
	@echo ">>> Pushed:"
	@echo "    docker.io/$$(DOCKER_USER)/kalki-$(1):$$(TAG)"
	@echo "    docker.io/$$(DOCKER_USER)/kalki-$(1):latest"
	$(PRUNE_CMD)

image-$(1): push-$(1)

build-$(1): builder
	docker buildx build \
	  --platform $$(PLATFORM) \
	  $$(BUILD_ARGS_$(1)) \
	  -t docker.io/$$(DOCKER_USER)/kalki-$(1):$$(TAG) \
	  -t docker.io/$$(DOCKER_USER)/kalki-$(1):latest \
	  --load \
	  ./$(1)
	$(PRUNE_CMD)

$(1): push-$(1)
endef

$(foreach svc,$(SERVICES),$(eval $(call SERVICE_RULES,$(svc))))

help:
	@echo "Kalki — Docker Hub publisher"
	@echo
	@echo "Build + push:"
	@echo "  make all                     Build + push every service"
	@echo "  make <service>               Build + push one service ($(SERVICES))"
	@echo "  make push-<service>          Explicit form of the above"
	@echo "  make image-<service>         Alias for push-<service>"
	@echo
	@echo "Local-only:"
	@echo "  make build-<service>         Build locally (--load), don't push"
	@echo
	@echo "Helpers:"
	@echo "  make login                   docker login docker.io"
	@echo "  make builder                 Ensure the buildx builder exists"
	@echo "  make prune                   docker system prune -f (reclaim disk)"
	@echo "  make clean                   Remove the buildx builder"
	@echo "  make help                    This screen"
	@echo
	@echo "Variables (override via env or 'make VAR=value'):"
	@echo "  DOCKER_USER    = $(DOCKER_USER)"
	@echo "  TAG            = $(TAG)"
	@echo "  GIT_SHA        = $(GIT_SHA)"
	@echo "  PLATFORM       = $(PLATFORM)   (Kalki cluster is amd64; buildx + QEMU cross-compile if needed)"
	@echo "  BUILDER        = $(BUILDER)"
	@echo "  PRUNE          = $(PRUNE)         (0 = skip post-build prune)"
	@echo "  BACKEND_URL    = $(BACKEND_URL)"
	@echo "  AUCTIONS_URL   = $(AUCTIONS_URL)"
	@echo "  AVIATOR_URL    = $(AVIATOR_URL)"
	@echo "  EXCHANGE_URL   = $(EXCHANGE_URL)"
	@echo "  ADMIN_URL      = $(ADMIN_URL)"
	@echo "  GOOGLE_ENABLED = $(GOOGLE_ENABLED)"
	@echo "  AVIATOR_ROCKET = $(AVIATOR_ROCKET)"
