import { ComingSoon } from "@/components/admin/ComingSoon";

export const dynamic = "force-dynamic";

export default function PayoutsPage() {
  return (
    <ComingSoon
      kicker="Finance"
      title="Payout management"
      description="Batch processor for resolution payouts with retry, audit, and manual adjustment."
      intent="Operator view of every payout generated by a market resolution. Status pipeline: PENDING → PROCESSING → SUCCEEDED / FAILED. Failed payouts get a retry button (idempotent by Transaction.reference); successful ones expose a manual reversal for fraud cases. Batch processor groups payouts by user to issue one wallet credit per user per resolved market."
      needs={[
        "Payout queue model: { resolutionId, userId, amountCoins, status, attempts, lastError, reference }.",
        "GET /api/admin/payouts?status=&marketId=&page=",
        "POST /api/admin/payouts/[id]/retry — idempotent re-run.",
        "POST /api/admin/payouts/[id]/reverse — generates compensating Transaction; audit logged.",
        "CSV export endpoint /api/admin/payouts/export?range= producing per-period payout reports.",
        "Note: the existing /api/admin/markets/[id]/resolve already does atomic in-line settlement (no separate queue). Adding this is a refactor — settlement starts writing Payout rows in PENDING and a worker drains them — not a pure additive change.",
      ]}
    />
  );
}
